config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'students_sessions/new'

  get 'sessions/new'

  get 'sessions/new'

  resources :educations
  resources :events
  resources :publications
  resources :research_interests
  resources :homepage
  get 'aboutus' => 'homepage#aboutus'
  get 'partnership' => 'homepage#partnership'
  get 'studentscorner' => 'homepage#studentscorner'
  
  root 'homepage#index'

  resources :faculties
  get 'login' => 'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'uin' => 'students#uin'
  get 'uin_search_results' => 'students#uin_search_results'
  get 'upload_resume' =>'faculties#upload_resume'
  resources :students
  get 'student_login' => 'students_sessions#new'
  get 'associate_student'=> 'faculties#associate_student'
  post 'student_login' => 'students_sessions#create'
  delete 'student_logout' => 'students_sessions#destroy'
  get 'error_display' => 'faculties#error_display'
  get 'students_error_display' => 'students#students_error_display'

end

app/models/student.rb
class Student < ActiveRecord::Base
 validates :name, :dept, :desc , presence: { :message => "data not present" }
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :publications
  has_and_belongs_to_many :research_interests, :join_table => "research_interests_students"
  has_and_belongs_to_many :faculties
  has_secure_password
  validates :password, length: { minimum: 6 }
  attr_accessor :remember_token
  extend FriendlyId
  friendly_id :name
  def Student.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Student.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = Student.new_token
    update_attribute(:remember_digest, Student.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
     self. where(['name ILIKE ? OR dept ILIKE ?', "%#{search}%", "%#{search}%"])
      
    else
      self.all
    end
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    #@student = Student.all
    @student = Student.order(params[:name])
    @student = Student.search(params[:search])
  end
  # GET /students/1
  # GET /students/1.json
  def show
  end
  def students_error_display
  end
  
  def uin
    
  end
  def uin_search_results
    uid=params[:uin]
    @student=Student.find_by_uin(uid)
    if @student == nil
      flash[:notice] = "No student with the UIN found"
      redirect_to uin_path
    end
    session[:uin] = uid
  end
  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    if  !session.key?(:student_id)
      redirect_to students_error_display_path
    end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :dept, :desc,:email,:password,:password_confirmation,:uin)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class= "row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit your profile</h1>
    <%= form_for(@student) do |f| %>
      <%= render 'form' %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :dept %><br>
        <%= f.text_field :dept, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :desc%><br>
        <%= f.text_area :desc,class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class ="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      <div class ="field">
        <%= f.label :password_confirmation %> <br>
        <%= f.password_field :password_confirmation ,class: 'form-control'%>
      </div>
      <div class="actions">
        <%= f.submit 'Create Account' ,class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Back', students_path %>
  </div>
</div>


<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Student's Corner</h1>
    <%= form_tag students_path, :method => 'get' do %>
    <p>
      <center><%= text_field_tag :search, params[:search], size: 150 %></center>
      <br>
      <div class=searchBarProperty>
        <%= submit_tag "Search for Students", class: "btn btn-primary" %>
      </div>
    </p>
    <% end %>
</center>
    <% @student.each do |student| %>
      
        <b><%= link_to "#{student.name}", student %></b> <br>
        <b>Department</b><br>
        <%= student.dept %><br>
        <b>About <%="#{student.name}"%></b><br>
        <b>UIN :</b><%=student.uin %><br>
        <%= student.desc %><br>
        <b>Email</b><br>
        <%= student.email %><br>
        <br>
        <br>
        <br>
    <% end %>


<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<div class= "row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Student - Sign up</h1>
    <%= form_for(@student) do |f| %>
      <%= render 'form' %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :dept %><br>
        <%= f.text_field :dept, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :desc%><br>
        <%= f.text_area :desc,class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :uin %><br>
        <%= f.text_field :uin, class: 'form-control' %>
      </div>
      <div class ="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      
      <div class ="field">
        <%= f.label :password_confirmation %> <br>
        <%= f.password_field :password_confirmation ,class: 'form-control'%>
      </div>
      <div class="actions">
        <%= f.submit 'Create Account' ,class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Back', students_path %>
  </div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @student.dept %>
</p>
<p>
  <strong>UIN:</strong>
  <%= @student.uin %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @student.desc %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/students/students_error_display.html.erb
<p>
    Please Login with correct details inorder to change details.
</p>

app/views/students/uin.html.erb
<%= form_tag uin_search_results_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :uin, params[:uin] %>
    <%= submit_tag "Search student by UIN", :name => nil,:class => 'btn btn_primary' %>
  </p>
<% end %>

app/views/students/uin_search_results.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @student.dept %>
</p>
<p>
  <strong>UIN:</strong>
  <%= @student.uin %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @student.desc %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
    <%= form_tag associate_student_path, :method => 'get' do %>
    <%= submit_tag 'confirm', :name => nil,:class => 'btn btn_primary' %>
    <%end%>
</p>