config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'students_sessions/new'

  get 'sessions/new'

  get 'sessions/new'

  resources :educations
  resources :events
  resources :publications
  resources :research_interests
  resources :homepage
  get 'aboutus' => 'homepage#aboutus'
  get 'partnership' => 'homepage#partnership'
  get 'studentscorner' => 'homepage#studentscorner'
  
  root 'homepage#index'

  resources :faculties
  get 'login' => 'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'uin' => 'students#uin'
  get 'uin_search_results' => 'students#uin_search_results'
  get 'upload_resume' =>'faculties#upload_resume'
  resources :students
  get 'student_login' => 'students_sessions#new'
  get 'associate_student'=> 'faculties#associate_student'
  post 'student_login' => 'students_sessions#create'
  delete 'student_logout' => 'students_sessions#destroy'
  get 'error_display' => 'faculties#error_display'
  get 'students_error_display' => 'students#students_error_display'

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  
  validates :name, :dept, :desc, :office, :phone_no, :email, presence: { :message => "data not present" }
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :publications
  has_and_belongs_to_many :research_interests, :join_table => "faculties_research_interests"
  has_and_belongs_to_many :students
  has_secure_password
  validates :password, length: { minimum: 6 }
  attr_accessor :remember_token
  
  extend FriendlyId
  friendly_id :name
  
  def Faculty.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Faculty.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = Faculty.new_token
    update_attribute(:remember_digest, Faculty.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
     self. where(['name ILIKE ? OR dept ILIKE ?', "%#{search}%", "%#{search}%"])
      
    else
      self.all
    end
  end
  
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    #@faculties = Faculty.all
    @faculties = Faculty.order(params[:name])
    @faculties = Faculty.search(params[:search])
    
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
    
  end
  
  def associate_student
    if session.key?(:faculty_id)
      @faculty=Faculty.find_by_id(session[:faculty_id])
      if @faculty == nil
        flash[:notice] = "You're not logged in"
        redirect_to uin_search_results_path
      else
      @student=Student.find_by_uin(session[:uin])
      @student1=@faculty.students.find_by_uin(session[:uin])
        if @student1 == nil
          @faculty.students << @student
        end
      session.delete(:uin)
      redirect_to faculty_path(@faculty)
      end
    else
      redirect_to error_display_path
    end
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
    if  !session.key?(:faculty_id)
      redirect_to error_display_path
    end
    @f=Faculty.find_by_name(params[:id])
    if @f.class==NilClass
     @f=Faculty.find_by_id(params[:id])
    end
    if session[:faculty_id] and session[:faculty_id]!=@f.id
      redirect_to error_display_path
    end
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)
    #@faculty.students << fu
    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    if session.key?(:faculty_id)
      respond_to do |format|
        if @faculty.update(faculty_params)
          format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
          format.json { render :show, status: :ok, location: @faculty }
        else
          format.html { render :edit }
          format.json { render json: @faculty.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to error_display_path
    end 
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def error_display
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :dept, :desc,:email,:office,:phone_no,:password,:password_confirmation,:uin)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<% if @faculty.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@faculty.errors.count, "error") %>.
    </div>
    <ul>
    <% @faculty.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<div class= "row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit your profile</h1>
    <%= form_for(@faculty) do |f| %>
      <%= render 'form' %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :dept %><br>
        <%= f.text_field :dept, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :desc%><br>
        <%= f.text_area :desc,class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :phone_no %><br>
        <%= f.text_field :phone_no, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :uin %><br>
        <%= f.text_field :uin, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :office %><br>
        <%= f.text_area :office ,class: 'form-control' %>
      </div>
      
      <div class ="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      
      <div class ="field">
        <%= f.label :password_confirmation %> <br>
        <%= f.password_field :password_confirmation ,class: 'form-control'%>
      </div>
      <div class="actions">
        <%= f.submit 'Create Account' ,class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Back', faculties_path %>
  </div>
</div>


<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/error_display.html.erb
<p>
    Please Login with correct details inorder to change details.
</p>

app/views/faculties/index.html.erb
<div class="details_positions">
    <p id="notice"><%= notice %></p>

<h1>Faculty Experts</h1>

    <%= form_tag faculties_path, :method => 'get' do %>
    <p>
      <center><%= text_field_tag :search, params[:search], size: 150 %></center>
      <br>
      <div class=searchBarProperty>
        <%= submit_tag "Search for Faculty Experts", class: "btn btn-primary" %>
      </div>
    </p>
    <% end %>
</center>
    <% @faculties.each do |faculty| %>
        <div class="element_spacing">
            <b><%= link_to "#{faculty.name}", faculty %></b> |
            <b>Department:</b>
            <%= faculty.dept %> | 
            <b> Email</b>
            <%= faculty.email %>
        </div>
    <% end %>


</div>

app/views/faculties/new.html.erb
<div class= "row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Faculty - Sign up</h1>
    <%= form_for(@faculty) do |f| %>
      <%= render 'form' %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :dept %><br>
        <%= f.text_field :dept, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :desc%><br>
        <%= f.text_area :desc,class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :phone_no %><br>
        <%= f.text_field :phone_no, class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :office %><br>
        <%= f.text_area :office ,class: 'form-control' %>
      </div>
      
      <div class ="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      
      <div class ="field">
        <%= f.label :password_confirmation %> <br>
        <%= f.password_field :password_confirmation ,class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :uin %><br>
        <%= f.text_field :uin, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit 'Create Account' ,class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Back', faculties_path %>
  </div>
</div>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @faculty.dept %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @faculty.desc %>
</p>

<p>
  <strong>Office:</strong>
  <%= @faculty.office %>
</p>
<p>
  <strong>UIN:</strong>
  <%= @faculty.uin %>
</p>
<p>
  <strong>Phone_no:</strong>
  <%= @faculty.phone_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @faculty.email %>
</p>

<p><b>My Students </b></p>
<% @faculty.students.each do |student| %>
Name: <%= link_to "#{student.name}",student_path(student) %><br>
<%end%>
<p><b>My publications</b></p>
<% @faculty.publications.each do |student| %>
<%= link_to "#{student.name}",publication_path(student) %><br>
<%end%>
<% if session.key?(:faculty_id) and session[:faculty_id] == @faculty.id%>
<%= link_to '<button type="button" class ="btn " id ="Add a new Student">Add new Student</button>'.html_safe, uin_path %> <br>

<%= form_tag new_resume_path, :method => 'get' do %>
  <p>
    <%= submit_tag "Upload CV", :name => nil %></br>
  </p>
<% end %>
<%= link_to 'Add a new publication',new_publication_path %> </br>
<%= link_to 'New Event', new_event_path %></br>
<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%end%>
<%= link_to 'Back', faculties_path %>

app/views/faculties/upload_resume.html.erb
<p>
  <strong>Status:</strong>
  <%= @upload_complete %>
</p>