config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'students_sessions/new'

  get 'sessions/new'

  get 'sessions/new'

  resources :educations
  resources :events
  resources :publications
  resources :research_interests
  resources :homepage
  get 'aboutus' => 'homepage#aboutus'
  get 'partnership' => 'homepage#partnership'
  get 'studentscorner' => 'homepage#studentscorner'
  
  root 'homepage#index'

  resources :faculties
  get 'login' => 'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'uin' => 'students#uin'
  get 'uin_search_results' => 'students#uin_search_results'
  get 'upload_resume' =>'faculties#upload_resume'
  resources :students
  get 'student_login' => 'students_sessions#new'
  get 'associate_student'=> 'faculties#associate_student'
  post 'student_login' => 'students_sessions#create'
  delete 'student_logout' => 'students_sessions#destroy'
  get 'error_display' => 'faculties#error_display'
  get 'students_error_display' => 'students#students_error_display'

end

app/views/shared/_navbar.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse roster">-->
<!--    <div class="container-fluid">-->
<!--      <div class= "headtitle">-->
<!--        <h1></h1>-->
<!--      </div>-->
<!--       <nav>-->
<!--        <ul class="nav navbar-nav navbar-right">-->
<!--          <li> <%= link_to "Home",'/' %> </li>-->
<!--          <li> <%= link_to "About us","#" %> </li>-->
<!--          <li> <%= link_to "Research",publications_path %> </li>-->
<!--            <li> <%= link_to "Education",educations_path %> </li>-->
<!--          <li> <%= link_to "Partnerships","#" %> </li>-->
<!--          <li> <%= link_to "Events",events_path %> </li>-->
<!--          <li> <%= link_to "Students corner","#" %> </li>-->
<!--          <li> <%= link_to "Find faculty experts",faculties_path %> </li>-->
<!--          <% if logged_in? %>-->
<!--          <li class="dropdown">-->
<!--            <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
<!--              Account <b class="caret"></b>-->
<!--            </a>-->
<!--            <ul class="dropdown-menu">-->
<!--              <li><%= link_to "Profile", current_faculty %></li>-->
<!--              <li><%= link_to "Edit my profile", faculty_path(session[:faculty_id]) %></li>-->
<!--              <li class="divider"></li>-->
<!--              <li>-->
<!--                <%= link_to "Log out", logout_path, method: "delete" %>-->
<!--                
<!--              </li>-->
<!--            </ul>-->
<!--          </li>-->
<!--          <% else %>-->
<!--          <li><%= link_to "faculty login",login_path %></li>-->
<!--          <% end %>-->
<!--        </ul>-->
        
<!--      </nav>-->
      
<!--    </div>-->
    
<!--  </header>-->
<!--  <div class="container-fluid">-->
<!--      <% flash.each do |message_type, message| %>-->
<!--        <div class="alert alert-<%= message_type %>"><%= message %></div>-->
<!--      <% end %>-->
<!--      <%= yield %>-->
<!--  </div>-->