config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'students_sessions/new'

  get 'sessions/new'

  get 'sessions/new'

  resources :educations
  resources :events
  resources :publications
  resources :research_interests
  resources :homepage
  get 'aboutus' => 'homepage#aboutus'
  get 'partnership' => 'homepage#partnership'
  get 'studentscorner' => 'homepage#studentscorner'
  
  root 'homepage#index'

  resources :faculties
  get 'login' => 'sessions#new'
  post 'login' =>'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'uin' => 'students#uin'
  get 'uin_search_results' => 'students#uin_search_results'
  get 'upload_resume' =>'faculties#upload_resume'
  resources :students
  get 'student_login' => 'students_sessions#new'
  get 'associate_student'=> 'faculties#associate_student'
  post 'student_login' => 'students_sessions#create'
  delete 'student_logout' => 'students_sessions#destroy'
  get 'error_display' => 'faculties#error_display'
  get 'students_error_display' => 'students#students_error_display'

end

app/models/education.rb
class Education < ActiveRecord::Base
validates :courses_offered, :course_number, :semester_offered, :course_category, presence: { :message => "data not present" }
  extend FriendlyId
  friendly_id :courses_offered
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  def index
    @educations = Education.all
  end
  def show
  end
  def new
    @education = Education.new
  end
  def edit
  end
  def create
    @education = Education.new(education_params)
    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_education
      @education = Education.friendly.find(params[:id])
    end
    def education_params
      params.require(:education).permit(:courses_offered, :course_number, :semester_offered, :course_category)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<div class="details_positions">
  <%= form_for(@education) do |f| %>
    <% if @education.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>
  
        <ul>
        <% @education.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :courses_offered %><br>
      <%= f.text_field :courses_offered %>
    </div>
    <div class="field">
      <%= f.label :course_number %><br>
      <%= f.text_field :course_number %>
    </div>
    <div class="field">
      <%= f.label :semester_offered %><br>
      <%= f.text_field :semester_offered %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>
<h1> EDUCATION </h1>
Texas A&M has a long history of providing information assurance and cybersecurity educational opportunities for its students. Dating back to the mid-1990s, A&M faculty developed the first academic courses that employed active attack-defense laboratory exercises that emphasized the importance of hands-on activities to facilitate and accelerate student learning. This then novel approach has now been widely adopted throughout educational and training settings where cybersecurity topics are taught. A&M students have benefited directly from these educational innovations and, through their studies and associated hands-on experiences, they have consistently been able to rapidly acquire important cybersecurity knowledge and skills.

Cybersecurity Designations and the Minor Field of Study in Cybersecurity were developed by the Texas A&M Cybersecurity Center to provide selected Texas A&M students with an opportunity to acquire specific cybersecurity knowledge and skills in order to prepare them for challenges they will face, upon graduation, in their personal and professional lives. The current cybersecurity offerings include three Cybersecurity Designations and one Cybersecurity Minor Field of Study. Each of these offering are described below.

<h2>Cybersecurity Curriculum Offerings</h2>
Policy and Operations Memorandum
<p id="notice"><%= notice %></p>

<div class="details_positions">
  <div class= "header_text" id="tag0"><h2>COURSE REQUIREMENTS FOR CYBERSECURITY MINOR FIELD OF STUDY</h2></div>
  
  <p>The Cybersecurity Minor is designed to appeal to both less technically-oriented and more technically-oriented undergraduate students, across multiple departments, in multiple colleges. All students who enroll in the minor will acquire a basic understanding of programming, and a firmly grounded understanding of cybersecurity, to include cyber ethics. Due to the interdisciplinary nature of cybersecurity this minor includes 20 undergraduate courses from colleges across the University. The inclusion of these courses in the minor will allow students to specialize in the area of cybersecurity that is most closely aligned with their respective interests and their degree plans.
  Below find links to the worksheet and application forms used by students to apply for a Cybersecurity Minor. The worksheet is to be used by the students and the Cybersecurity Center Designation and Minor Coordinator to ensure that all Cybersecurity Minor Field of Study requirements are met.
  Available to all students pursuing a Bachelor of Science (B.S.) and a Bachelor of Arts (B.A.)
  </p>
  
  <h3>Available to all students pursuing a Bachelor of Science (B.S.) and a Bachelor of Arts (B.A.)</h3>
  <div class="col-md-6">
  <table class = "table-hover">
    <thead>
      <tr>
        <th> Courses offered   </th>
        <th> Course number   </th>
        <th> Semester offered  </th>
        
      </tr>
    </thead>
  
    <tbody>
      <% Education.where(:course_category => "A").each do |education| %>
        <tr>
          <td><%= education.courses_offered %></td>
          <td><%= education.course_number %></td>
          <td><%= education.semester_offered %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="col-md-12"  >
    <div class= "header_text" id="tag1" ><h2 text-position:center>COURSE REQUIREMENTS FOR UNDERGRADUATE CYBERSECURITY DESIGNATION (THEORY)</h2></div>
  
  <p>The Undergraduate Cybersecurity Designation (Theory) is designed to provide a broad technically-oriented education, firmly grounded in theory, for students who intends to pursue a career involving cybersecurity, or more broadly, software and system development. These students will be equipped to pursue employment in a variety of both private and public settings. They will be able to engage in either research, development, or operations involving information or operational technologies.  Many of these students will continue their education, pursuing advanced degrees. The designation focuses on classical computing theory, with an emphasis on software development and application. This Designation focuses on the application of computer science, computer engineering, and cybersecurity theories.
  Below find links to the worksheet and application forms used by students to apply for a Cybersecurity Designation. The worksheet is to be used by the students and the Cybersecurity Center Designation and Minor Coordinator to ensure that all Undergraduate Cybersecurity Designation (Theory) requirements are met.
  Available to students pursuing a Bachelor of Science (B.S.) or Bachelor of Arts (B.A.)</p>
  
  <h3>Required Computer Science Courses (must take all eight courses)</h3>
  </div>
  
  <div class="col-md-6">
  <table class = "table-hover">
    <thead>
      <tr>
        <th>Courses offered</th>
        <th>Course number</th>
        <th>Semester offered</th>
       
      </tr>
    </thead>
  
    <tbody>
      <% Education.where(:course_category => "B").each do |education| %>
        <tr>
          <td><%= education.courses_offered %></td>
          <td><%= education.course_number %></td>
          <td><%= education.semester_offered %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  
  <div class="col-md-12">
     <div class= "header_text" id="tag2"><h2>COURSE REQUIREMENTS FOR UNDERGRADUATE CYBERSECURITY DESIGNATION (APPLICATION)</h2></div>
  
  <p style="page-break-after:always;">The Undergraduate Cybersecurity Designation (Theory) is designed to provide a broad technically-oriented education, firmly grounded in theory, for students who intends to pursue a career involving cybersecurity, or more broadly, software and system development. These students will be equipped to pursue employment in a variety of both private and public settings. They will be able to engage in either research, development, or operations involving information or operational technologies.  Many of these students will continue their education, pursuing advanced degrees. The designation focuses on classical computing theory, with an emphasis on software development and application. This Designation focuses on the application of computer science, computer engineering, and cybersecurity theories.
  Below find links to the worksheet and application forms used by students to apply for a Cybersecurity Designation. The worksheet is to be used by the students and the Cybersecurity Center Designation and Minor Coordinator to ensure that all Undergraduate Cybersecurity Designation (Theory) requirements are met.
  Available to students pursuing a Bachelor of Science (B.S.) or Bachelor of Arts (B.A.)
  </p>
  
  <h3><p>Required Computer Science Courses (must take all eight courses)</p></h3>
  </div>
  
  <div class="col-md-6">
  <table class = "table-hover">
    <thead>
      <tr>
        <th>Courses offered</th>
        <th>Course number</th>
        <th>Semester offered</th>
       
      </tr>
    </thead>
  
    <tbody>
      <% Education.where(:course_category => "C" ).each do |education| %>
        <tr>
          <td><%= education.courses_offered %></td>
          <td><%= education.course_number %></td>
          <td><%= education.semester_offered %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="col-md-12">
    <div class= "header_text" id="tag3"><h2>COURSE REQUIREMENTS FOR GRADUATE CYBERSECURITY DESIGNATION</h2></div>
  <p style="page-break-after:always;">
  The Graduate Cybersecurity Designation is designed to provide an in-depth and technically-oriented education, firmly grounded in theory, for graduate students who intend to pursue a career involving cybersecurity, or more broadly, software and system development. These students will be equipped to pursue employment in a variety of both private and public settings.  In particular, they will be ideally suited to engage in basic and applied research in academic, government, or public settings.
  Below find links to the worksheet and application forms used by students to apply for a Cybersecurity Designation. The worksheet is to be used by the students and the Cybersecurity Center Designation and Minor Coordinator to ensure that all Graduate Cybersecurity Designation requirements are met.
  Available to students pursuing a Master’s of Science (M.S.) or Doctorate of Philosophy (Ph.D.)
  </p>
  
  
  <h3>Listing Coursework</h3>
  
  </div>
  
  <div class="col-md-6">
  <table class = "table-hover">
    <thead>
      <tr>
        <th>Courses offered</th>
        <th>Course number</th>
        <th>Semester offered</th>
      </tr>
    </thead>
  
    <tbody>
      <% Education.where(:course_category => 'D').each do |education| %>
        <tr>
          <td><%= education.courses_offered %></td>
          <td><%= education.course_number %></td>
          <td><%= education.semester_offered %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="col-md-12">
    <h1>Faculty</h1>
  
  <p style="page-break-after:always;">Texas A&M faculty are involved in research that addresses a broad array of important cybersecurity topics. Moreover, the sheer number of publications produced by these scholars, as well as the thousands of citations to their scholarly works combined, indicate that A&M researchers are making significant contributions to the advancement of cybersecurity knowledge. Because the A&M faculty is so large and diverse, their research is not restricted to a small number of specific areas or approaches that may lose their relevance over time. The cybersecurity research topics addressed by A&M faculty span the full range of scholarly inquiry, from foundational basic research to problem-oriented applied research.
  </p>
  <div>
   <%= form_tag faculties_path, :method => 'get' do %>
      <p>
        <%= submit_tag "Find Faculty Experts", :name => nil %>
      </p>
  <% end %> 
  </div>
  </div>
  
</div>

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Courses offered:</strong>
  <%= @education.courses_offered %>
</p>

<p>
  <strong>Course number:</strong>
  <%= @education.course_number %>
</p>

<p>
  <strong>Semester offered:</strong>
  <%= @education.semester_offered %>
</p>

<p>
  <strong>Course Category:</strong>
  <%= @education.course_category %>
</p>  

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>